# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PWMs_res.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_PWMs(object):
    def setupUi(self, Form_PWMs):
        Form_PWMs.setObjectName(_fromUtf8("Form_PWMs"))
        Form_PWMs.resize(870, 708)
        self.pushButton_prevPWM = QtGui.QPushButton(Form_PWMs)
        self.pushButton_prevPWM.setEnabled(False)
        self.pushButton_prevPWM.setGeometry(QtCore.QRect(540, 150, 75, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prevPWM.setIcon(icon)
        self.pushButton_prevPWM.setObjectName(_fromUtf8("pushButton_prevPWM"))
        self.pushButton_nextPWM = QtGui.QPushButton(Form_PWMs)
        self.pushButton_nextPWM.setEnabled(False)
        self.pushButton_nextPWM.setGeometry(QtCore.QRect(540, 210, 75, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_nextPWM.setIcon(icon1)
        self.pushButton_nextPWM.setObjectName(_fromUtf8("pushButton_nextPWM"))
        self.pushButton_readmem = QtGui.QPushButton(Form_PWMs)
        self.pushButton_readmem.setGeometry(QtCore.QRect(430, 180, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readmem.setFont(font)
        self.pushButton_readmem.setObjectName(_fromUtf8("pushButton_readmem"))
        self.pushButton_logstart = QtGui.QPushButton(Form_PWMs)
        self.pushButton_logstart.setGeometry(QtCore.QRect(430, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logstart.setFont(font)
        self.pushButton_logstart.setObjectName(_fromUtf8("pushButton_logstart"))
        self.checkBox_offline = QtGui.QCheckBox(Form_PWMs)
        self.checkBox_offline.setGeometry(QtCore.QRect(433, 150, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_offline.setFont(font)
        self.checkBox_offline.setObjectName(_fromUtf8("checkBox_offline"))
        self.spinBox_MemDataSelect = QtGui.QSpinBox(Form_PWMs)
        self.spinBox_MemDataSelect.setEnabled(True)
        self.spinBox_MemDataSelect.setGeometry(QtCore.QRect(440, 220, 42, 22))
        self.spinBox_MemDataSelect.setMinimum(0)
        self.spinBox_MemDataSelect.setProperty("value", 0)
        self.spinBox_MemDataSelect.setObjectName(_fromUtf8("spinBox_MemDataSelect"))
        self.pushButton_saveMemDataToFile = QtGui.QPushButton(Form_PWMs)
        self.pushButton_saveMemDataToFile.setGeometry(QtCore.QRect(430, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_saveMemDataToFile.setFont(font)
        self.pushButton_saveMemDataToFile.setObjectName(_fromUtf8("pushButton_saveMemDataToFile"))
        self.tableWidget_PWM = QtGui.QTableWidget(Form_PWMs)
        self.tableWidget_PWM.setGeometry(QtCore.QRect(10, 20, 362, 242))
        self.tableWidget_PWM.setRowCount(8)
        self.tableWidget_PWM.setColumnCount(8)
        self.tableWidget_PWM.setObjectName(_fromUtf8("tableWidget_PWM"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 7, item)
        self.tableWidget_PWM.horizontalHeader().setVisible(False)
        self.tableWidget_PWM.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_PWM.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_PWM.verticalHeader().setVisible(False)
        self.tableWidget_PWM.verticalHeader().setHighlightSections(True)
        self.graphicsView_PWM = QtGui.QGraphicsView(Form_PWMs)
        self.graphicsView_PWM.setGeometry(QtCore.QRect(10, 310, 840, 300))
        self.graphicsView_PWM.setObjectName(_fromUtf8("graphicsView_PWM"))
        self.lineEdit_PWMfile = QtGui.QLineEdit(Form_PWMs)
        self.lineEdit_PWMfile.setGeometry(QtCore.QRect(540, 75, 180, 20))
        self.lineEdit_PWMfile.setObjectName(_fromUtf8("lineEdit_PWMfile"))
        self.pushButton_chooseFile = QtGui.QPushButton(Form_PWMs)
        self.pushButton_chooseFile.setGeometry(QtCore.QRect(730, 73, 75, 23))
        self.pushButton_chooseFile.setObjectName(_fromUtf8("pushButton_chooseFile"))
        self.label_Status = QtGui.QLabel(Form_PWMs)
        self.label_Status.setGeometry(QtCore.QRect(20, 280, 400, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Status.setFont(font)
        self.label_Status.setText(_fromUtf8(""))
        self.label_Status.setObjectName(_fromUtf8("label_Status"))

        self.retranslateUi(Form_PWMs)
        QtCore.QMetaObject.connectSlotsByName(Form_PWMs)

    def retranslateUi(self, Form_PWMs):
        Form_PWMs.setWindowTitle(_translate("Form_PWMs", "Form_PWMs", None))
        self.pushButton_prevPWM.setText(_translate("Form_PWMs", "PREV", None))
        self.pushButton_nextPWM.setText(_translate("Form_PWMs", "NEXT", None))
        self.pushButton_readmem.setText(_translate("Form_PWMs", "ReadMem", None))
        self.pushButton_logstart.setText(_translate("Form_PWMs", "LogStart", None))
        self.checkBox_offline.setText(_translate("Form_PWMs", "offline", None))
        self.pushButton_saveMemDataToFile.setText(_translate("Form_PWMs", "SaveToFile", None))
        __sortingEnabled = self.tableWidget_PWM.isSortingEnabled()
        self.tableWidget_PWM.setSortingEnabled(False)
        item = self.tableWidget_PWM.item(0, 0)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(0, 1)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(0, 2)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(0, 3)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(0, 4)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(0, 5)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(0, 6)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(0, 7)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(1, 0)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(1, 1)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(1, 2)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(1, 3)
        item.setText(_translate("Form_PWMs", "1", None))
        item = self.tableWidget_PWM.item(1, 4)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(1, 5)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(1, 6)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(1, 7)
        item.setText(_translate("Form_PWMs", "0", None))
        item = self.tableWidget_PWM.item(2, 0)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(2, 1)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(2, 2)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(2, 3)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(2, 4)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(2, 5)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(2, 6)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(2, 7)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(3, 0)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(3, 1)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(3, 2)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(3, 3)
        item.setText(_translate("Form_PWMs", "3", None))
        item = self.tableWidget_PWM.item(3, 4)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(3, 5)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(3, 6)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(3, 7)
        item.setText(_translate("Form_PWMs", "2", None))
        item = self.tableWidget_PWM.item(4, 0)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(4, 1)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(4, 2)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(4, 3)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(4, 4)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(4, 5)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(4, 6)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(4, 7)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(5, 0)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(5, 1)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(5, 2)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(5, 3)
        item.setText(_translate("Form_PWMs", "5", None))
        item = self.tableWidget_PWM.item(5, 4)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(5, 5)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(5, 6)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(5, 7)
        item.setText(_translate("Form_PWMs", "4", None))
        item = self.tableWidget_PWM.item(6, 0)
        item.setText(_translate("Form_PWMs", "6", None))
        item = self.tableWidget_PWM.item(6, 1)
        item.setText(_translate("Form_PWMs", "6", None))
        item = self.tableWidget_PWM.item(6, 2)
        item.setText(_translate("Form_PWMs", "6", None))
        item = self.tableWidget_PWM.item(6, 3)
        item.setText(_translate("Form_PWMs", "6", None))
        item = self.tableWidget_PWM.item(6, 4)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(6, 5)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(6, 6)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(6, 7)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(7, 0)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(7, 1)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(7, 2)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(7, 3)
        item.setText(_translate("Form_PWMs", "7", None))
        item = self.tableWidget_PWM.item(7, 4)
        item.setText(_translate("Form_PWMs", "6", None))
        item = self.tableWidget_PWM.item(7, 5)
        item.setText(_translate("Form_PWMs", "6", None))
        item = self.tableWidget_PWM.item(7, 6)
        item.setText(_translate("Form_PWMs", "6", None))
        item = self.tableWidget_PWM.item(7, 7)
        item.setText(_translate("Form_PWMs", "6", None))
        self.tableWidget_PWM.setSortingEnabled(__sortingEnabled)
        self.pushButton_chooseFile.setText(_translate("Form_PWMs", "Choose File", None))

