# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dimmingdebugger_res.ui'
#
# Created: Wed Apr 27 22:00:37 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(867, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("222.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(440, 10, 381, 291))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidget_PWM = QtGui.QTableWidget(self.tab)
        self.tableWidget_PWM.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.tableWidget_PWM.setRowCount(8)
        self.tableWidget_PWM.setColumnCount(8)
        self.tableWidget_PWM.setObjectName(_fromUtf8("tableWidget_PWM"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 7, item)
        self.tableWidget_PWM.horizontalHeader().setVisible(False)
        self.tableWidget_PWM.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_PWM.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_PWM.verticalHeader().setVisible(False)
        self.tableWidget_PWM.verticalHeader().setHighlightSections(True)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget_Current = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_Current.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.tableWidget_Current.setRowCount(8)
        self.tableWidget_Current.setColumnCount(8)
        self.tableWidget_Current.setObjectName(_fromUtf8("tableWidget_Current"))
        self.tableWidget_Current.horizontalHeader().setVisible(False)
        self.tableWidget_Current.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_Current.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tableWidget_dc2dc = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_dc2dc.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.tableWidget_dc2dc.setRowCount(8)
        self.tableWidget_dc2dc.setColumnCount(8)
        self.tableWidget_dc2dc.setObjectName(_fromUtf8("tableWidget_dc2dc"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(5, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(6, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_dc2dc.setItem(7, 7, item)
        self.tableWidget_dc2dc.horizontalHeader().setVisible(False)
        self.tableWidget_dc2dc.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_dc2dc.verticalHeader().setVisible(False)
        self.tableWidget_dc2dc.verticalHeader().setHighlightSections(False)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.pushButton_readpwm = QtGui.QPushButton(self.centralwidget)
        self.pushButton_readpwm.setGeometry(QtCore.QRect(350, 40, 75, 23))
        self.pushButton_readpwm.setObjectName(_fromUtf8("pushButton_readpwm"))
        self.pushButton_readcurrent = QtGui.QPushButton(self.centralwidget)
        self.pushButton_readcurrent.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.pushButton_readcurrent.setObjectName(_fromUtf8("pushButton_readcurrent"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(440, 330, 381, 291))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tableWidget_PWM_2 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_PWM_2.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.tableWidget_PWM_2.setRowCount(8)
        self.tableWidget_PWM_2.setColumnCount(8)
        self.tableWidget_PWM_2.setObjectName(_fromUtf8("tableWidget_PWM_2"))
        self.tableWidget_PWM_2.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_PWM_2.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_PWM_2.verticalHeader().setVisible(False)
        self.tableWidget_PWM_2.verticalHeader().setHighlightSections(False)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tableWidget_Current_2 = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_Current_2.setGeometry(QtCore.QRect(0, 0, 401, 271))
        self.tableWidget_Current_2.setRowCount(8)
        self.tableWidget_Current_2.setColumnCount(8)
        self.tableWidget_Current_2.setObjectName(_fromUtf8("tableWidget_Current_2"))
        self.tableWidget_Current_2.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_Current_2.verticalHeader().setVisible(False)
        self.tableWidget_Current_2.verticalHeader().setHighlightSections(False)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.pushButton_A1 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_A1.setGeometry(QtCore.QRect(350, 350, 75, 23))
        self.pushButton_A1.setObjectName(_fromUtf8("pushButton_A1"))
        self.pushButton_A2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_A2.setGeometry(QtCore.QRect(350, 400, 75, 23))
        self.pushButton_A2.setObjectName(_fromUtf8("pushButton_A2"))
        self.pushButton_A3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_A3.setGeometry(QtCore.QRect(350, 450, 75, 23))
        self.pushButton_A3.setObjectName(_fromUtf8("pushButton_A3"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, 310, 491, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.tableWidget_Paras = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_Paras.setGeometry(QtCore.QRect(10, 30, 251, 321))
        self.tableWidget_Paras.setObjectName(_fromUtf8("tableWidget_Paras"))
        self.tableWidget_Paras.setColumnCount(1)
        self.tableWidget_Paras.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Paras.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Paras.setHorizontalHeaderItem(0, item)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_write = QtGui.QPushButton(self.centralwidget)
        self.pushButton_write.setGeometry(QtCore.QRect(350, 510, 75, 23))
        self.pushButton_write.setObjectName(_fromUtf8("pushButton_write"))
        self.pushButton_flushimg = QtGui.QPushButton(self.centralwidget)
        self.pushButton_flushimg.setGeometry(QtCore.QRect(350, 280, 75, 23))
        self.pushButton_flushimg.setObjectName(_fromUtf8("pushButton_flushimg"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setToolTip(_fromUtf8(""))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_setting_file = QtGui.QAction(MainWindow)
        self.actionOpen_setting_file.setObjectName(_fromUtf8("actionOpen_setting_file"))
        self.actionSave_setting_file = QtGui.QAction(MainWindow)
        self.actionSave_setting_file.setObjectName(_fromUtf8("actionSave_setting_file"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.menuFile.addAction(self.actionOpen_setting_file)
        self.menuFile.addAction(self.actionSave_setting_file)
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionConnect)
        self.menuSetting.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dimming Debugger     DisConnect..", None))
        __sortingEnabled = self.tableWidget_PWM.isSortingEnabled()
        self.tableWidget_PWM.setSortingEnabled(False)
        item = self.tableWidget_PWM.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 4)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(0, 5)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(0, 6)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(0, 7)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 3)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(1, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(1, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(1, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(2, 0)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 2)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 3)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 4)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(2, 5)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(2, 6)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(2, 7)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 0)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 3)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 4)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(3, 5)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(3, 6)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(3, 7)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(4, 0)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 1)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 2)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(4, 5)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(4, 6)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(4, 7)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 0)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 1)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 2)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 3)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 4)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(5, 5)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(5, 6)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(5, 7)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(6, 0)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 1)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 2)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 3)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 4)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(6, 5)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(6, 6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(6, 7)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 0)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 1)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 2)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 3)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 4)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(7, 5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(7, 6)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(7, 7)
        item.setText(_translate("MainWindow", "6", None))
        self.tableWidget_PWM.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "PWMs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Currents", None))
        __sortingEnabled = self.tableWidget_dc2dc.isSortingEnabled()
        self.tableWidget_dc2dc.setSortingEnabled(False)
        item = self.tableWidget_dc2dc.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(0, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(0, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(0, 4)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(0, 5)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(0, 6)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(0, 7)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(1, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(1, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(1, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(1, 3)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_dc2dc.item(1, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(1, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(1, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(1, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_dc2dc.item(2, 0)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(2, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(2, 2)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(2, 3)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(2, 4)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(2, 5)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(2, 6)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(2, 7)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(3, 0)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(3, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(3, 2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_dc2dc.item(3, 3)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(3, 4)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(3, 5)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(3, 6)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(3, 7)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_dc2dc.item(4, 0)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(4, 1)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(4, 2)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(4, 3)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(4, 4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(4, 5)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(4, 6)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(4, 7)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(5, 0)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(5, 1)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(5, 2)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_dc2dc.item(5, 3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(5, 4)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(5, 5)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(5, 6)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(5, 7)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_dc2dc.item(6, 0)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_dc2dc.item(6, 1)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_dc2dc.item(6, 2)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_dc2dc.item(6, 3)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_dc2dc.item(6, 4)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(6, 5)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(6, 6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(6, 7)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(7, 0)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(7, 1)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(7, 2)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(7, 3)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_dc2dc.item(7, 4)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_dc2dc.item(7, 5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_dc2dc.item(7, 6)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_dc2dc.item(7, 7)
        item.setText(_translate("MainWindow", "6", None))
        self.tableWidget_dc2dc.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "DC2DC", None))
        self.pushButton_readpwm.setText(_translate("MainWindow", "ReadPWM", None))
        self.pushButton_readcurrent.setText(_translate("MainWindow", "ReadCurrent", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "PWMs", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Currents", None))
        self.pushButton_A1.setText(_translate("MainWindow", "Algo_A1", None))
        self.pushButton_A2.setText(_translate("MainWindow", "Algo_A2", None))
        self.pushButton_A3.setText(_translate("MainWindow", "Algo_A3", None))
        item = self.tableWidget_Paras.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "paras", None))
        item = self.tableWidget_Paras.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value", None))
        self.label.setText(_translate("MainWindow", "Parameters:", None))
        self.pushButton_write.setText(_translate("MainWindow", "WriteChip", None))
        self.pushButton_flushimg.setText(_translate("MainWindow", "Flushimg", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_setting_file.setText(_translate("MainWindow", "Open setting file", None))
        self.actionSave_setting_file.setText(_translate("MainWindow", "Save setting file", None))
        self.actionQuit.setText(_translate("MainWindow", "quit", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))

