# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dimmingdebugger_res.ui'
#
# Created: Wed Mar 15 13:32:19 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("222.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_prev = QtGui.QPushButton(self.tab)
        self.pushButton_prev.setEnabled(False)
        self.pushButton_prev.setGeometry(QtCore.QRect(540, 150, 75, 41))
        self.pushButton_prev.setObjectName(_fromUtf8("pushButton_prev"))
        self.pushButton_next = QtGui.QPushButton(self.tab)
        self.pushButton_next.setEnabled(False)
        self.pushButton_next.setGeometry(QtCore.QRect(540, 210, 75, 41))
        self.pushButton_next.setObjectName(_fromUtf8("pushButton_next"))
        self.pushButton_readmem = QtGui.QPushButton(self.tab)
        self.pushButton_readmem.setGeometry(QtCore.QRect(430, 180, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readmem.setFont(font)
        self.pushButton_readmem.setObjectName(_fromUtf8("pushButton_readmem"))
        self.pushButton_logstart = QtGui.QPushButton(self.tab)
        self.pushButton_logstart.setGeometry(QtCore.QRect(430, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logstart.setFont(font)
        self.pushButton_logstart.setObjectName(_fromUtf8("pushButton_logstart"))
        self.checkBox_offline = QtGui.QCheckBox(self.tab)
        self.checkBox_offline.setGeometry(QtCore.QRect(433, 150, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_offline.setFont(font)
        self.checkBox_offline.setObjectName(_fromUtf8("checkBox_offline"))
        self.spinBox_MemDataSelect = QtGui.QSpinBox(self.tab)
        self.spinBox_MemDataSelect.setEnabled(True)
        self.spinBox_MemDataSelect.setGeometry(QtCore.QRect(440, 220, 42, 22))
        self.spinBox_MemDataSelect.setMinimum(0)
        self.spinBox_MemDataSelect.setProperty("value", 0)
        self.spinBox_MemDataSelect.setObjectName(_fromUtf8("spinBox_MemDataSelect"))
        self.pushButton_saveMemDataToFile = QtGui.QPushButton(self.tab)
        self.pushButton_saveMemDataToFile.setGeometry(QtCore.QRect(430, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_saveMemDataToFile.setFont(font)
        self.pushButton_saveMemDataToFile.setObjectName(_fromUtf8("pushButton_saveMemDataToFile"))
        self.tableWidget_PWM = QtGui.QTableWidget(self.tab)
        self.tableWidget_PWM.setGeometry(QtCore.QRect(10, 10, 362, 242))
        self.tableWidget_PWM.setRowCount(8)
        self.tableWidget_PWM.setColumnCount(8)
        self.tableWidget_PWM.setObjectName(_fromUtf8("tableWidget_PWM"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(5, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(6, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_PWM.setItem(7, 7, item)
        self.tableWidget_PWM.horizontalHeader().setVisible(False)
        self.tableWidget_PWM.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_PWM.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_PWM.verticalHeader().setVisible(False)
        self.tableWidget_PWM.verticalHeader().setHighlightSections(True)
        self.graphicsView_PWM = QtGui.QGraphicsView(self.tab)
        self.graphicsView_PWM.setGeometry(QtCore.QRect(10, 310, 840, 300))
        self.graphicsView_PWM.setObjectName(_fromUtf8("graphicsView_PWM"))
        self.lineEdit_PWMfile = QtGui.QLineEdit(self.tab)
        self.lineEdit_PWMfile.setGeometry(QtCore.QRect(540, 75, 180, 20))
        self.lineEdit_PWMfile.setObjectName(_fromUtf8("lineEdit_PWMfile"))
        self.pushButton_chooseFile = QtGui.QPushButton(self.tab)
        self.pushButton_chooseFile.setGeometry(QtCore.QRect(730, 73, 75, 23))
        self.pushButton_chooseFile.setObjectName(_fromUtf8("pushButton_chooseFile"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget_Hist = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_Hist.setGeometry(QtCore.QRect(10, 20, 362, 242))
        self.tableWidget_Hist.setRowCount(8)
        self.tableWidget_Hist.setColumnCount(8)
        self.tableWidget_Hist.setObjectName(_fromUtf8("tableWidget_Hist"))
        self.tableWidget_Hist.horizontalHeader().setVisible(False)
        self.tableWidget_Hist.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_Hist.horizontalHeader().setHighlightSections(False)
        self.tableWidget_Hist.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_Hist.verticalHeader().setVisible(False)
        self.graphicsView_Hist = QtGui.QGraphicsView(self.tab_2)
        self.graphicsView_Hist.setGeometry(QtCore.QRect(10, 310, 831, 321))
        self.graphicsView_Hist.setObjectName(_fromUtf8("graphicsView_Hist"))
        self.pushButton_readHist = QtGui.QPushButton(self.tab_2)
        self.pushButton_readHist.setGeometry(QtCore.QRect(460, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readHist.setFont(font)
        self.pushButton_readHist.setObjectName(_fromUtf8("pushButton_readHist"))
        self.spinBox_HistDataSelect = QtGui.QSpinBox(self.tab_2)
        self.spinBox_HistDataSelect.setGeometry(QtCore.QRect(580, 50, 61, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_HistDataSelect.setFont(font)
        self.spinBox_HistDataSelect.setObjectName(_fromUtf8("spinBox_HistDataSelect"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(650, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setToolTip(_fromUtf8(""))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_setting_file = QtGui.QAction(MainWindow)
        self.actionOpen_setting_file.setObjectName(_fromUtf8("actionOpen_setting_file"))
        self.actionSave_setting_file = QtGui.QAction(MainWindow)
        self.actionSave_setting_file.setObjectName(_fromUtf8("actionSave_setting_file"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.menuFile.addAction(self.actionOpen_setting_file)
        self.menuFile.addAction(self.actionSave_setting_file)
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionConnect)
        self.menuSetting.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dimming Debugger     DisConnect..", None))
        self.pushButton_prev.setText(_translate("MainWindow", "PREV", None))
        self.pushButton_next.setText(_translate("MainWindow", "NEXT", None))
        self.pushButton_readmem.setText(_translate("MainWindow", "ReadMem", None))
        self.pushButton_logstart.setText(_translate("MainWindow", "LogStart", None))
        self.checkBox_offline.setText(_translate("MainWindow", "offline", None))
        self.pushButton_saveMemDataToFile.setText(_translate("MainWindow", "SaveToFile", None))
        __sortingEnabled = self.tableWidget_PWM.isSortingEnabled()
        self.tableWidget_PWM.setSortingEnabled(False)
        item = self.tableWidget_PWM.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(0, 4)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(0, 5)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(0, 6)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(0, 7)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 3)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_PWM.item(1, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(1, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(1, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(1, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_PWM.item(2, 0)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 2)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 3)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(2, 4)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(2, 5)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(2, 6)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(2, 7)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 0)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 3)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_PWM.item(3, 4)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(3, 5)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(3, 6)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(3, 7)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_PWM.item(4, 0)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 1)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 2)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(4, 4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(4, 5)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(4, 6)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(4, 7)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 0)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 1)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 2)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 3)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_PWM.item(5, 4)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(5, 5)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(5, 6)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(5, 7)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_PWM.item(6, 0)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 1)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 2)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 3)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(6, 4)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(6, 5)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(6, 6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(6, 7)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 0)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 1)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 2)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 3)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_PWM.item(7, 4)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(7, 5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(7, 6)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_PWM.item(7, 7)
        item.setText(_translate("MainWindow", "6", None))
        self.tableWidget_PWM.setSortingEnabled(__sortingEnabled)
        self.pushButton_chooseFile.setText(_translate("MainWindow", "Choose File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "PWMs", None))
        self.pushButton_readHist.setText(_translate("MainWindow", "ReadHist", None))
        self.label.setText(_translate("MainWindow", "Hist Index:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Hist", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_setting_file.setText(_translate("MainWindow", "Open setting file", None))
        self.actionSave_setting_file.setText(_translate("MainWindow", "Save setting file", None))
        self.actionQuit.setText(_translate("MainWindow", "quit", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))

