# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dimpages.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_Dimpages(object):
    def setupUi(self, Form_Dimpages):
        Form_Dimpages.setObjectName(_fromUtf8("Form_Dimpages"))
        Form_Dimpages.resize(1012, 744)
        self.tableWidget_curpage = QtGui.QTableWidget(Form_Dimpages)
        self.tableWidget_curpage.setGeometry(QtCore.QRect(170, 0, 601, 521))
        self.tableWidget_curpage.setObjectName(_fromUtf8("tableWidget_curpage"))
        self.tableWidget_curpage.setColumnCount(4)
        self.tableWidget_curpage.setRowCount(16)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_curpage.setItem(0, 0, item)
        self.tableWidget_curpage.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_curpage.horizontalHeader().setDefaultSectionSize(100)
        self.treeWidget_pages = QtGui.QTreeWidget(Form_Dimpages)
        self.treeWidget_pages.setEnabled(True)
        self.treeWidget_pages.setGeometry(QtCore.QRect(10, 0, 161, 701))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.treeWidget_pages.setFont(font)
        self.treeWidget_pages.setAutoFillBackground(False)
        self.treeWidget_pages.setStyleSheet(_fromUtf8("border-color: rgb(85, 170, 0);"))
        self.treeWidget_pages.setFrameShadow(QtGui.QFrame.Plain)
        self.treeWidget_pages.setAlternatingRowColors(False)
        self.treeWidget_pages.setIndentation(28)
        self.treeWidget_pages.setItemsExpandable(True)
        self.treeWidget_pages.setAnimated(False)
        self.treeWidget_pages.setAllColumnsShowFocus(True)
        self.treeWidget_pages.setWordWrap(True)
        self.treeWidget_pages.setHeaderHidden(False)
        self.treeWidget_pages.setObjectName(_fromUtf8("treeWidget_pages"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_pages)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_pages)
        self.textEdit_curregdes = QtGui.QTextEdit(Form_Dimpages)
        self.textEdit_curregdes.setGeometry(QtCore.QRect(170, 520, 601, 181))
        self.textEdit_curregdes.setObjectName(_fromUtf8("textEdit_curregdes"))
        self.gridLayoutWidget_2 = QtGui.QWidget(Form_Dimpages)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(780, 40, 160, 115))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_1 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_1.setObjectName(_fromUtf8("gridLayout_1"))
        self.label_0_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_3.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);\n"
"gridline-color: rgb(0, 0, 0);"))
        self.label_0_3.setText(_fromUtf8(""))
        self.label_0_3.setObjectName(_fromUtf8("label_0_3"))
        self.gridLayout_1.addWidget(self.label_0_3, 3, 0, 1, 1)
        self.label_0_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.label_0_2.setText(_fromUtf8(""))
        self.label_0_2.setObjectName(_fromUtf8("label_0_2"))
        self.gridLayout_1.addWidget(self.label_0_2, 2, 0, 1, 1)
        self.label_0_1 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_1.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 255);"))
        self.label_0_1.setText(_fromUtf8(""))
        self.label_0_1.setObjectName(_fromUtf8("label_0_1"))
        self.gridLayout_1.addWidget(self.label_0_1, 1, 0, 1, 1)
        self.label_0_0 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_0.setAutoFillBackground(False)
        self.label_0_0.setStyleSheet(_fromUtf8("background-color: rgb(125, 125, 125);\n"
"border-color: rgb(0, 0, 0);"))
        self.label_0_0.setText(_fromUtf8(""))
        self.label_0_0.setObjectName(_fromUtf8("label_0_0"))
        self.gridLayout_1.addWidget(self.label_0_0, 0, 0, 1, 1)
        self.label_1_0 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_0.setFont(font)
        self.label_1_0.setObjectName(_fromUtf8("label_1_0"))
        self.gridLayout_1.addWidget(self.label_1_0, 0, 1, 1, 1)
        self.label_1_1 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_1.setFont(font)
        self.label_1_1.setObjectName(_fromUtf8("label_1_1"))
        self.gridLayout_1.addWidget(self.label_1_1, 1, 1, 1, 1)
        self.label_1_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_2.setFont(font)
        self.label_1_2.setObjectName(_fromUtf8("label_1_2"))
        self.gridLayout_1.addWidget(self.label_1_2, 2, 1, 1, 1)
        self.label_1_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_3.setFont(font)
        self.label_1_3.setObjectName(_fromUtf8("label_1_3"))
        self.gridLayout_1.addWidget(self.label_1_3, 3, 1, 1, 1)
        self.label = QtGui.QLabel(Form_Dimpages)
        self.label.setGeometry(QtCore.QRect(780, 20, 151, 16))
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(Form_Dimpages)
        self.label_3.setGeometry(QtCore.QRect(860, 220, 76, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.widget = QtGui.QWidget(Form_Dimpages)
        self.widget.setGeometry(QtCore.QRect(780, 220, 71, 29))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet(_fromUtf8("background-color: rgb(229, 229, 229);\n"
"border-left-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 255);"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label_2 = QtGui.QLabel(Form_Dimpages)
        self.label_2.setGeometry(QtCore.QRect(790, 300, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(Form_Dimpages)
        self.label_4.setGeometry(QtCore.QRect(790, 320, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))

        self.retranslateUi(Form_Dimpages)
        QtCore.QMetaObject.connectSlotsByName(Form_Dimpages)

    def retranslateUi(self, Form_Dimpages):
        Form_Dimpages.setWindowTitle(_translate("Form_Dimpages", "Form_Dimpages", None))
        item = self.tableWidget_curpage.verticalHeaderItem(0)
        item.setText(_translate("Form_Dimpages", "00", None))
        item = self.tableWidget_curpage.verticalHeaderItem(1)
        item.setText(_translate("Form_Dimpages", "10", None))
        item = self.tableWidget_curpage.verticalHeaderItem(2)
        item.setText(_translate("Form_Dimpages", "20", None))
        item = self.tableWidget_curpage.verticalHeaderItem(3)
        item.setText(_translate("Form_Dimpages", "30", None))
        item = self.tableWidget_curpage.verticalHeaderItem(4)
        item.setText(_translate("Form_Dimpages", "40", None))
        item = self.tableWidget_curpage.verticalHeaderItem(5)
        item.setText(_translate("Form_Dimpages", "50", None))
        item = self.tableWidget_curpage.verticalHeaderItem(6)
        item.setText(_translate("Form_Dimpages", "60", None))
        item = self.tableWidget_curpage.verticalHeaderItem(7)
        item.setText(_translate("Form_Dimpages", "70", None))
        item = self.tableWidget_curpage.verticalHeaderItem(8)
        item.setText(_translate("Form_Dimpages", "80", None))
        item = self.tableWidget_curpage.verticalHeaderItem(9)
        item.setText(_translate("Form_Dimpages", "90", None))
        item = self.tableWidget_curpage.verticalHeaderItem(10)
        item.setText(_translate("Form_Dimpages", "A0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(11)
        item.setText(_translate("Form_Dimpages", "B0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(12)
        item.setText(_translate("Form_Dimpages", "C0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(13)
        item.setText(_translate("Form_Dimpages", "D0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(14)
        item.setText(_translate("Form_Dimpages", "E0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(15)
        item.setText(_translate("Form_Dimpages", "F0", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(0)
        item.setText(_translate("Form_Dimpages", "00", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(1)
        item.setText(_translate("Form_Dimpages", "04", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(2)
        item.setText(_translate("Form_Dimpages", "08", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(3)
        item.setText(_translate("Form_Dimpages", "0C", None))
        __sortingEnabled = self.tableWidget_curpage.isSortingEnabled()
        self.tableWidget_curpage.setSortingEnabled(False)
        self.tableWidget_curpage.setSortingEnabled(__sortingEnabled)
        self.treeWidget_pages.setSortingEnabled(False)
        self.treeWidget_pages.headerItem().setText(0, _translate("Form_Dimpages", "V_PANEL", None))
        __sortingEnabled = self.treeWidget_pages.isSortingEnabled()
        self.treeWidget_pages.setSortingEnabled(False)
        self.treeWidget_pages.topLevelItem(0).setText(0, _translate("Form_Dimpages", "2DDIM_PIXC", None))
        self.treeWidget_pages.topLevelItem(1).setText(0, _translate("Form_Dimpages", "2DDIM_HIST", None))
        self.treeWidget_pages.setSortingEnabled(__sortingEnabled)
        self.label_1_0.setText(_translate("Form_Dimpages", "Not Use", None))
        self.label_1_1.setText(_translate("Form_Dimpages", "Read Only", None))
        self.label_1_2.setText(_translate("Form_Dimpages", "Write Only", None))
        self.label_1_3.setText(_translate("Form_Dimpages", "Read | Write", None))
        self.label.setText(_translate("Form_Dimpages", "Access Legend", None))
        self.label_3.setText(_translate("Form_Dimpages", "TSE Common", None))
        self.label_2.setText(_translate("Form_Dimpages", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff0000;\">ADD</span><span style=\" font-size:10pt;\">: 19A00400</span></p></body></html>", None))
        self.label_4.setText(_translate("Form_Dimpages", "DWORD Mode", None))

