# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dimpages_res.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_Dimpages(object):
    def setupUi(self, Form_Dimpages):
        Form_Dimpages.setObjectName(_fromUtf8("Form_Dimpages"))
        Form_Dimpages.resize(1012, 744)
        self.tableWidget_curpage = QtGui.QTableWidget(Form_Dimpages)
        self.tableWidget_curpage.setGeometry(QtCore.QRect(170, 0, 601, 507))
        self.tableWidget_curpage.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableWidget_curpage.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_curpage.setObjectName(_fromUtf8("tableWidget_curpage"))
        self.tableWidget_curpage.setColumnCount(4)
        self.tableWidget_curpage.setRowCount(16)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setVerticalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_curpage.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_curpage.setItem(0, 0, item)
        self.tableWidget_curpage.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_curpage.horizontalHeader().setDefaultSectionSize(143)
        self.tableWidget_curpage.horizontalHeader().setHighlightSections(False)
        self.tableWidget_curpage.verticalHeader().setHighlightSections(False)
        self.treeWidget_pages = QtGui.QTreeWidget(Form_Dimpages)
        self.treeWidget_pages.setEnabled(True)
        self.treeWidget_pages.setGeometry(QtCore.QRect(10, 157, 161, 531))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.treeWidget_pages.setFont(font)
        self.treeWidget_pages.setAutoFillBackground(False)
        self.treeWidget_pages.setStyleSheet(_fromUtf8("border-color: rgb(85, 170, 0);"))
        self.treeWidget_pages.setFrameShadow(QtGui.QFrame.Plain)
        self.treeWidget_pages.setAlternatingRowColors(False)
        self.treeWidget_pages.setIndentation(28)
        self.treeWidget_pages.setItemsExpandable(True)
        self.treeWidget_pages.setAnimated(False)
        self.treeWidget_pages.setAllColumnsShowFocus(True)
        self.treeWidget_pages.setWordWrap(True)
        self.treeWidget_pages.setHeaderHidden(False)
        self.treeWidget_pages.setColumnCount(1)
        self.treeWidget_pages.setObjectName(_fromUtf8("treeWidget_pages"))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_pages.headerItem().setFont(0, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_pages)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_pages)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setBackground(0, brush)
        self.textEdit_curregdes = QtGui.QTextEdit(Form_Dimpages)
        self.textEdit_curregdes.setGeometry(QtCore.QRect(170, 507, 601, 181))
        self.textEdit_curregdes.setReadOnly(True)
        self.textEdit_curregdes.setObjectName(_fromUtf8("textEdit_curregdes"))
        self.gridLayoutWidget_2 = QtGui.QWidget(Form_Dimpages)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(780, 40, 160, 115))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_1 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_1.setObjectName(_fromUtf8("gridLayout_1"))
        self.label_0_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_3.setStyleSheet(_fromUtf8("background-color: rgb(232, 232, 232);\n"
"gridline-color: rgb(0, 0, 0);"))
        self.label_0_3.setText(_fromUtf8(""))
        self.label_0_3.setObjectName(_fromUtf8("label_0_3"))
        self.gridLayout_1.addWidget(self.label_0_3, 3, 0, 1, 1)
        self.label_0_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_2.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.label_0_2.setText(_fromUtf8(""))
        self.label_0_2.setObjectName(_fromUtf8("label_0_2"))
        self.gridLayout_1.addWidget(self.label_0_2, 2, 0, 1, 1)
        self.label_0_1 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_1.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 255);"))
        self.label_0_1.setText(_fromUtf8(""))
        self.label_0_1.setObjectName(_fromUtf8("label_0_1"))
        self.gridLayout_1.addWidget(self.label_0_1, 1, 0, 1, 1)
        self.label_0_0 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_0_0.setAutoFillBackground(False)
        self.label_0_0.setStyleSheet(_fromUtf8("background-color: rgb(125, 125, 125);\n"
"border-color: rgb(0, 0, 0);"))
        self.label_0_0.setText(_fromUtf8(""))
        self.label_0_0.setObjectName(_fromUtf8("label_0_0"))
        self.gridLayout_1.addWidget(self.label_0_0, 0, 0, 1, 1)
        self.label_1_0 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_0.setFont(font)
        self.label_1_0.setObjectName(_fromUtf8("label_1_0"))
        self.gridLayout_1.addWidget(self.label_1_0, 0, 1, 1, 1)
        self.label_1_1 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_1.setFont(font)
        self.label_1_1.setObjectName(_fromUtf8("label_1_1"))
        self.gridLayout_1.addWidget(self.label_1_1, 1, 1, 1, 1)
        self.label_1_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_2.setFont(font)
        self.label_1_2.setObjectName(_fromUtf8("label_1_2"))
        self.gridLayout_1.addWidget(self.label_1_2, 2, 1, 1, 1)
        self.label_1_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1_3.setFont(font)
        self.label_1_3.setObjectName(_fromUtf8("label_1_3"))
        self.gridLayout_1.addWidget(self.label_1_3, 3, 1, 1, 1)
        self.label = QtGui.QLabel(Form_Dimpages)
        self.label.setGeometry(QtCore.QRect(780, 20, 151, 16))
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form_Dimpages)
        self.label_2.setGeometry(QtCore.QRect(780, 190, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(Form_Dimpages)
        self.label_4.setGeometry(QtCore.QRect(780, 210, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayoutWidget = QtGui.QWidget(Form_Dimpages)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(780, 400, 160, 101))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_writepage = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_writepage.setObjectName(_fromUtf8("pushButton_writepage"))
        self.gridLayout.addWidget(self.pushButton_writepage, 0, 1, 1, 1)
        self.pushButton_getitem = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_getitem.setObjectName(_fromUtf8("pushButton_getitem"))
        self.gridLayout.addWidget(self.pushButton_getitem, 1, 1, 1, 1)
        self.pushButton_readpage = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_readpage.setObjectName(_fromUtf8("pushButton_readpage"))
        self.gridLayout.addWidget(self.pushButton_readpage, 0, 0, 1, 1)
        self.pushButton_refresh = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_refresh.setObjectName(_fromUtf8("pushButton_refresh"))
        self.gridLayout.addWidget(self.pushButton_refresh, 1, 0, 1, 1)
        self.label_addr = QtGui.QLabel(Form_Dimpages)
        self.label_addr.setGeometry(QtCore.QRect(810, 191, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_addr.setFont(font)
        self.label_addr.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_addr.setObjectName(_fromUtf8("label_addr"))
        self.groupBox = QtGui.QGroupBox(Form_Dimpages)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 171, 71))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 11, 160, 51))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_7 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.gridLayout_2.addWidget(self.radioButton_7, 0, 0, 1, 1)
        self.radioButton_15 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.gridLayout_2.addWidget(self.radioButton_15, 1, 0, 1, 1)
        self.radioButton_23 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_23.setObjectName(_fromUtf8("radioButton_23"))
        self.gridLayout_2.addWidget(self.radioButton_23, 0, 1, 1, 1)
        self.radioButton_31 = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.radioButton_31.setObjectName(_fromUtf8("radioButton_31"))
        self.gridLayout_2.addWidget(self.radioButton_31, 1, 1, 1, 1)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Form_Dimpages)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 100, 161, 51))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_31 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_2.addWidget(self.label_31)
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_2.addWidget(self.label_30)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_2.addWidget(self.label_29)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_2.addWidget(self.label_28)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_2.addWidget(self.label_27)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_2.addWidget(self.label_26)
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_2.addWidget(self.label_25)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_2.addWidget(self.label_24)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_7 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_7.setText(_fromUtf8(""))
        self.checkBox_7.setTristate(False)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.horizontalLayout.addWidget(self.checkBox_7)
        self.checkBox_6 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_6.setText(_fromUtf8(""))
        self.checkBox_6.setTristate(False)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.horizontalLayout.addWidget(self.checkBox_6)
        self.checkBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setTristate(False)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.checkBox_4 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setTristate(False)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_3 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_1 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_1.setText(_fromUtf8(""))
        self.checkBox_1.setTristate(False)
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.horizontalLayout.addWidget(self.checkBox_1)
        self.checkBox_0 = QtGui.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_0.setText(_fromUtf8(""))
        self.checkBox_0.setTristate(False)
        self.checkBox_0.setObjectName(_fromUtf8("checkBox_0"))
        self.horizontalLayout.addWidget(self.checkBox_0)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.label_regsname = QtGui.QLabel(Form_Dimpages)
        self.label_regsname.setGeometry(QtCore.QRect(30, 10, 111, 16))
        self.label_regsname.setStyleSheet(_fromUtf8("color: rgb(0, 85, 255);"))
        self.label_regsname.setObjectName(_fromUtf8("label_regsname"))

        self.retranslateUi(Form_Dimpages)
        QtCore.QMetaObject.connectSlotsByName(Form_Dimpages)

    def retranslateUi(self, Form_Dimpages):
        Form_Dimpages.setWindowTitle(_translate("Form_Dimpages", "Form_Dimpages", None))
        item = self.tableWidget_curpage.verticalHeaderItem(0)
        item.setText(_translate("Form_Dimpages", "00", None))
        item = self.tableWidget_curpage.verticalHeaderItem(1)
        item.setText(_translate("Form_Dimpages", "10", None))
        item = self.tableWidget_curpage.verticalHeaderItem(2)
        item.setText(_translate("Form_Dimpages", "20", None))
        item = self.tableWidget_curpage.verticalHeaderItem(3)
        item.setText(_translate("Form_Dimpages", "30", None))
        item = self.tableWidget_curpage.verticalHeaderItem(4)
        item.setText(_translate("Form_Dimpages", "40", None))
        item = self.tableWidget_curpage.verticalHeaderItem(5)
        item.setText(_translate("Form_Dimpages", "50", None))
        item = self.tableWidget_curpage.verticalHeaderItem(6)
        item.setText(_translate("Form_Dimpages", "60", None))
        item = self.tableWidget_curpage.verticalHeaderItem(7)
        item.setText(_translate("Form_Dimpages", "70", None))
        item = self.tableWidget_curpage.verticalHeaderItem(8)
        item.setText(_translate("Form_Dimpages", "80", None))
        item = self.tableWidget_curpage.verticalHeaderItem(9)
        item.setText(_translate("Form_Dimpages", "90", None))
        item = self.tableWidget_curpage.verticalHeaderItem(10)
        item.setText(_translate("Form_Dimpages", "A0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(11)
        item.setText(_translate("Form_Dimpages", "B0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(12)
        item.setText(_translate("Form_Dimpages", "C0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(13)
        item.setText(_translate("Form_Dimpages", "D0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(14)
        item.setText(_translate("Form_Dimpages", "E0", None))
        item = self.tableWidget_curpage.verticalHeaderItem(15)
        item.setText(_translate("Form_Dimpages", "F0", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(0)
        item.setText(_translate("Form_Dimpages", "00", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(1)
        item.setText(_translate("Form_Dimpages", "04", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(2)
        item.setText(_translate("Form_Dimpages", "08", None))
        item = self.tableWidget_curpage.horizontalHeaderItem(3)
        item.setText(_translate("Form_Dimpages", "0C", None))
        __sortingEnabled = self.tableWidget_curpage.isSortingEnabled()
        self.tableWidget_curpage.setSortingEnabled(False)
        self.tableWidget_curpage.setSortingEnabled(__sortingEnabled)
        self.treeWidget_pages.setSortingEnabled(False)
        self.treeWidget_pages.headerItem().setText(0, _translate("Form_Dimpages", "V_PANEL", None))
        __sortingEnabled = self.treeWidget_pages.isSortingEnabled()
        self.treeWidget_pages.setSortingEnabled(False)
        self.treeWidget_pages.topLevelItem(0).setText(0, _translate("Form_Dimpages", "2DDIM_HIST", None))
        self.treeWidget_pages.topLevelItem(1).setText(0, _translate("Form_Dimpages", "2DDIM_PIXC", None))
        self.treeWidget_pages.setSortingEnabled(__sortingEnabled)
        self.label_1_0.setText(_translate("Form_Dimpages", "Not Use", None))
        self.label_1_1.setText(_translate("Form_Dimpages", "Read Only", None))
        self.label_1_2.setText(_translate("Form_Dimpages", "Write Only", None))
        self.label_1_3.setText(_translate("Form_Dimpages", "Read | Write", None))
        self.label.setText(_translate("Form_Dimpages", "Access Legend", None))
        self.label_2.setText(_translate("Form_Dimpages", "<html><head/><body><p><span style=\" color:#ff0000;\">ADD</span>:</p></body></html>", None))
        self.label_4.setText(_translate("Form_Dimpages", "DWORD Mode", None))
        self.pushButton_writepage.setText(_translate("Form_Dimpages", "Write", None))
        self.pushButton_getitem.setText(_translate("Form_Dimpages", "GetItem", None))
        self.pushButton_readpage.setText(_translate("Form_Dimpages", "Read", None))
        self.pushButton_refresh.setText(_translate("Form_Dimpages", "Refresh", None))
        self.label_addr.setText(_translate("Form_Dimpages", "19A00400", None))
        self.radioButton_7.setText(_translate("Form_Dimpages", "7-0", None))
        self.radioButton_15.setText(_translate("Form_Dimpages", "15-8", None))
        self.radioButton_23.setText(_translate("Form_Dimpages", "23-16", None))
        self.radioButton_31.setText(_translate("Form_Dimpages", "31-24", None))
        self.label_31.setText(_translate("Form_Dimpages", "31", None))
        self.label_30.setText(_translate("Form_Dimpages", "30", None))
        self.label_29.setText(_translate("Form_Dimpages", "29", None))
        self.label_28.setText(_translate("Form_Dimpages", "28", None))
        self.label_27.setText(_translate("Form_Dimpages", "27", None))
        self.label_26.setText(_translate("Form_Dimpages", "26", None))
        self.label_25.setText(_translate("Form_Dimpages", "25", None))
        self.label_24.setText(_translate("Form_Dimpages", "24", None))
        self.label_regsname.setText(_translate("Form_Dimpages", "spare:spare", None))

