# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestPattern_res.ui'
#
# Created: Mon Mar 27 17:35:10 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_TestPattern(object):
    def setupUi(self, Form_TestPattern):
        Form_TestPattern.setObjectName(_fromUtf8("Form_TestPattern"))
        Form_TestPattern.resize(870, 708)
        self.plainTextEdi_pats = QtGui.QPlainTextEdit(Form_TestPattern)
        self.plainTextEdi_pats.setGeometry(QtCore.QRect(440, 40, 371, 581))
        self.plainTextEdi_pats.setObjectName(_fromUtf8("plainTextEdi_pats"))
        self.label_patdelay = QtGui.QLabel(Form_TestPattern)
        self.label_patdelay.setGeometry(QtCore.QRect(20, 590, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_patdelay.setFont(font)
        self.label_patdelay.setObjectName(_fromUtf8("label_patdelay"))
        self.spinBox_patdelays = QtGui.QSpinBox(Form_TestPattern)
        self.spinBox_patdelays.setEnabled(True)
        self.spinBox_patdelays.setGeometry(QtCore.QRect(320, 590, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_patdelays.setFont(font)
        self.spinBox_patdelays.setMinimum(1)
        self.spinBox_patdelays.setMaximum(9999)
        self.spinBox_patdelays.setProperty("value", 1)
        self.spinBox_patdelays.setObjectName(_fromUtf8("spinBox_patdelays"))
        self.tableWidget_pattern = QtGui.QTableWidget(Form_TestPattern)
        self.tableWidget_pattern.setGeometry(QtCore.QRect(20, 310, 381, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_pattern.setFont(font)
        self.tableWidget_pattern.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_pattern.setAutoFillBackground(False)
        self.tableWidget_pattern.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget_pattern.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.tableWidget_pattern.setRowCount(8)
        self.tableWidget_pattern.setColumnCount(8)
        self.tableWidget_pattern.setObjectName(_fromUtf8("tableWidget_pattern"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 7, item)
        self.tableWidget_pattern.horizontalHeader().setVisible(False)
        self.tableWidget_pattern.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_pattern.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_pattern.verticalHeader().setVisible(False)
        self.tableWidget_pattern.verticalHeader().setHighlightSections(True)
        self.label_paneinfo_1 = QtGui.QLabel(Form_TestPattern)
        self.label_paneinfo_1.setGeometry(QtCore.QRect(440, 0, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_paneinfo_1.setFont(font)
        self.label_paneinfo_1.setObjectName(_fromUtf8("label_paneinfo_1"))
        self.verticalLayoutWidget = QtGui.QWidget(Form_TestPattern)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 10, 181, 261))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_readpanel = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readpanel.setFont(font)
        self.pushButton_readpanel.setObjectName(_fromUtf8("pushButton_readpanel"))
        self.verticalLayout.addWidget(self.pushButton_readpanel)
        self.pushButton_addpattern = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addpattern.setFont(font)
        self.pushButton_addpattern.setObjectName(_fromUtf8("pushButton_addpattern"))
        self.verticalLayout.addWidget(self.pushButton_addpattern)
        self.pushButton_delpattern = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delpattern.setFont(font)
        self.pushButton_delpattern.setObjectName(_fromUtf8("pushButton_delpattern"))
        self.verticalLayout.addWidget(self.pushButton_delpattern)
        self.pushButton_savecurrentpat = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_savecurrentpat.setFont(font)
        self.pushButton_savecurrentpat.setObjectName(_fromUtf8("pushButton_savecurrentpat"))
        self.verticalLayout.addWidget(self.pushButton_savecurrentpat)
        self.pushButton_sendpattochip = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sendpattochip.setFont(font)
        self.pushButton_sendpattochip.setObjectName(_fromUtf8("pushButton_sendpattochip"))
        self.verticalLayout.addWidget(self.pushButton_sendpattochip)
        self.pushButton_readfromchip = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readfromchip.setFont(font)
        self.pushButton_readfromchip.setObjectName(_fromUtf8("pushButton_readfromchip"))
        self.verticalLayout.addWidget(self.pushButton_readfromchip)
        self.gridLayoutWidget = QtGui.QWidget(Form_TestPattern)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 101))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_next = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_next.setEnabled(True)
        self.pushButton_next.setObjectName(_fromUtf8("pushButton_next"))
        self.gridLayout.addWidget(self.pushButton_next, 0, 1, 1, 1)
        self.pushButton_savepatToFile = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_savepatToFile.setEnabled(True)
        self.pushButton_savepatToFile.setObjectName(_fromUtf8("pushButton_savepatToFile"))
        self.gridLayout.addWidget(self.pushButton_savepatToFile, 0, 0, 1, 1)
        self.pushButton_prev = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_prev.setEnabled(True)
        self.pushButton_prev.setObjectName(_fromUtf8("pushButton_prev"))
        self.gridLayout.addWidget(self.pushButton_prev, 1, 1, 1, 1)
        self.pushButton_loadpatfromFile = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_loadpatfromFile.setEnabled(True)
        self.pushButton_loadpatfromFile.setObjectName(_fromUtf8("pushButton_loadpatfromFile"))
        self.gridLayout.addWidget(self.pushButton_loadpatfromFile, 1, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form_TestPattern)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 221, 101))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_patindex = QtGui.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_patindex.setFont(font)
        self.label_patindex.setObjectName(_fromUtf8("label_patindex"))
        self.verticalLayout_2.addWidget(self.label_patindex)
        self.lineEdit_index = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_index.setReadOnly(True)
        self.lineEdit_index.setObjectName(_fromUtf8("lineEdit_index"))
        self.verticalLayout_2.addWidget(self.lineEdit_index)
        self.comboBox_listpats = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox_listpats.setObjectName(_fromUtf8("comboBox_listpats"))
        self.verticalLayout_2.addWidget(self.comboBox_listpats)
        self.pushButton_disable = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_disable.setObjectName(_fromUtf8("pushButton_disable"))
        self.verticalLayout_2.addWidget(self.pushButton_disable)

        self.retranslateUi(Form_TestPattern)
        QtCore.QMetaObject.connectSlotsByName(Form_TestPattern)

    def retranslateUi(self, Form_TestPattern):
        Form_TestPattern.setWindowTitle(_translate("Form_TestPattern", "Form_TestPattern", None))
        self.label_patdelay.setText(_translate("Form_TestPattern", "Current Pat delay time(s):", None))
        __sortingEnabled = self.tableWidget_pattern.isSortingEnabled()
        self.tableWidget_pattern.setSortingEnabled(False)
        item = self.tableWidget_pattern.item(0, 0)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 1)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 2)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 3)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 4)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(0, 5)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(0, 6)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(0, 7)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 0)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 1)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 2)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 3)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 4)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(1, 5)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(1, 6)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(1, 7)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(2, 0)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 1)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 2)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 3)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 4)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(2, 5)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(2, 6)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(2, 7)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 0)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 1)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 2)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 3)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 4)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(3, 5)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(3, 6)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(3, 7)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(4, 0)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 1)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 2)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 3)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 4)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(4, 5)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(4, 6)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(4, 7)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 0)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 1)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 2)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 3)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 4)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(5, 5)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(5, 6)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(5, 7)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(6, 0)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 1)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 2)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 3)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 4)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(6, 5)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(6, 6)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(6, 7)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 0)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 1)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 2)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 3)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 4)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(7, 5)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(7, 6)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(7, 7)
        item.setText(_translate("Form_TestPattern", "6", None))
        self.tableWidget_pattern.setSortingEnabled(__sortingEnabled)
        self.label_paneinfo_1.setText(_translate("Form_TestPattern", "No panel info!!", None))
        self.pushButton_readpanel.setText(_translate("Form_TestPattern", "GetPanelInfo", None))
        self.pushButton_addpattern.setText(_translate("Form_TestPattern", "AddPat", None))
        self.pushButton_delpattern.setText(_translate("Form_TestPattern", "DelPat", None))
        self.pushButton_savecurrentpat.setText(_translate("Form_TestPattern", "SaveCurPat", None))
        self.pushButton_sendpattochip.setText(_translate("Form_TestPattern", "SendToChip", None))
        self.pushButton_readfromchip.setText(_translate("Form_TestPattern", "ReadFromChip", None))
        self.pushButton_next.setText(_translate("Form_TestPattern", "NEXT", None))
        self.pushButton_savepatToFile.setText(_translate("Form_TestPattern", "SaveToFile", None))
        self.pushButton_prev.setText(_translate("Form_TestPattern", "PREV", None))
        self.pushButton_loadpatfromFile.setText(_translate("Form_TestPattern", "LoadfromFile", None))
        self.label_patindex.setText(_translate("Form_TestPattern", "Pattern Index:", None))
        self.lineEdit_index.setText(_translate("Form_TestPattern", "TEMP", None))
        self.pushButton_disable.setText(_translate("Form_TestPattern", "DisManualPats", None))

