# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestPattern_res.ui'
#
# Created: Tue Mar 21 15:26:48 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form_TestPattern(object):
    def setupUi(self, Form_TestPattern):
        Form_TestPattern.setObjectName(_fromUtf8("Form_TestPattern"))
        Form_TestPattern.resize(870, 708)
        self.pushButton_addpattern = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_addpattern.setGeometry(QtCore.QRect(270, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addpattern.setFont(font)
        self.pushButton_addpattern.setObjectName(_fromUtf8("pushButton_addpattern"))
        self.spinBox_patselect = QtGui.QSpinBox(Form_TestPattern)
        self.spinBox_patselect.setEnabled(True)
        self.spinBox_patselect.setGeometry(QtCore.QRect(150, 160, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_patselect.setFont(font)
        self.spinBox_patselect.setMinimum(1)
        self.spinBox_patselect.setMaximum(100)
        self.spinBox_patselect.setProperty("value", 1)
        self.spinBox_patselect.setObjectName(_fromUtf8("spinBox_patselect"))
        self.pushButton_savepatToFile = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_savepatToFile.setEnabled(True)
        self.pushButton_savepatToFile.setGeometry(QtCore.QRect(30, 10, 91, 41))
        self.pushButton_savepatToFile.setObjectName(_fromUtf8("pushButton_savepatToFile"))
        self.pushButton_prev = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_prev.setEnabled(True)
        self.pushButton_prev.setGeometry(QtCore.QRect(130, 60, 91, 41))
        self.pushButton_prev.setObjectName(_fromUtf8("pushButton_prev"))
        self.pushButton_next = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_next.setEnabled(True)
        self.pushButton_next.setGeometry(QtCore.QRect(130, 10, 91, 41))
        self.pushButton_next.setObjectName(_fromUtf8("pushButton_next"))
        self.label_patindex = QtGui.QLabel(Form_TestPattern)
        self.label_patindex.setGeometry(QtCore.QRect(20, 170, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_patindex.setFont(font)
        self.label_patindex.setObjectName(_fromUtf8("label_patindex"))
        self.pushButton_readpanel = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_readpanel.setGeometry(QtCore.QRect(270, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readpanel.setFont(font)
        self.pushButton_readpanel.setObjectName(_fromUtf8("pushButton_readpanel"))
        self.pushButton_loadpatfromFile = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_loadpatfromFile.setEnabled(True)
        self.pushButton_loadpatfromFile.setGeometry(QtCore.QRect(30, 60, 91, 41))
        self.pushButton_loadpatfromFile.setObjectName(_fromUtf8("pushButton_loadpatfromFile"))
        self.plainTextEdi_pats = QtGui.QPlainTextEdit(Form_TestPattern)
        self.plainTextEdi_pats.setGeometry(QtCore.QRect(430, 40, 371, 581))
        self.plainTextEdi_pats.setObjectName(_fromUtf8("plainTextEdi_pats"))
        self.label_patdelay = QtGui.QLabel(Form_TestPattern)
        self.label_patdelay.setGeometry(QtCore.QRect(20, 590, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_patdelay.setFont(font)
        self.label_patdelay.setObjectName(_fromUtf8("label_patdelay"))
        self.spinBox_patdelays = QtGui.QSpinBox(Form_TestPattern)
        self.spinBox_patdelays.setEnabled(True)
        self.spinBox_patdelays.setGeometry(QtCore.QRect(290, 590, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_patdelays.setFont(font)
        self.spinBox_patdelays.setMinimum(1)
        self.spinBox_patdelays.setMaximum(500)
        self.spinBox_patdelays.setProperty("value", 1)
        self.spinBox_patdelays.setObjectName(_fromUtf8("spinBox_patdelays"))
        self.pushButton_delpattern = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_delpattern.setGeometry(QtCore.QRect(270, 120, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delpattern.setFont(font)
        self.pushButton_delpattern.setObjectName(_fromUtf8("pushButton_delpattern"))
        self.pushButton_sendpattochip = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_sendpattochip.setGeometry(QtCore.QRect(220, 250, 181, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sendpattochip.setFont(font)
        self.pushButton_sendpattochip.setObjectName(_fromUtf8("pushButton_sendpattochip"))
        self.pushButton_savecurrentpat = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_savecurrentpat.setGeometry(QtCore.QRect(270, 170, 121, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_savecurrentpat.setFont(font)
        self.pushButton_savecurrentpat.setObjectName(_fromUtf8("pushButton_savecurrentpat"))
        self.pushButton_readfromchip = QtGui.QPushButton(Form_TestPattern)
        self.pushButton_readfromchip.setGeometry(QtCore.QRect(20, 250, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readfromchip.setFont(font)
        self.pushButton_readfromchip.setObjectName(_fromUtf8("pushButton_readfromchip"))
        self.comboBox_listpats = QtGui.QComboBox(Form_TestPattern)
        self.comboBox_listpats.setGeometry(QtCore.QRect(30, 110, 91, 22))
        self.comboBox_listpats.setObjectName(_fromUtf8("comboBox_listpats"))
        self.tableWidget_pattern = QtGui.QTableWidget(Form_TestPattern)
        self.tableWidget_pattern.setGeometry(QtCore.QRect(20, 310, 381, 261))
        self.tableWidget_pattern.setRowCount(8)
        self.tableWidget_pattern.setColumnCount(8)
        self.tableWidget_pattern.setObjectName(_fromUtf8("tableWidget_pattern"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 7, item)
        self.tableWidget_pattern.horizontalHeader().setVisible(False)
        self.tableWidget_pattern.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_pattern.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_pattern.verticalHeader().setVisible(False)
        self.tableWidget_pattern.verticalHeader().setHighlightSections(True)
        self.label_paneinfo_1 = QtGui.QLabel(Form_TestPattern)
        self.label_paneinfo_1.setGeometry(QtCore.QRect(430, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_paneinfo_1.setFont(font)
        self.label_paneinfo_1.setObjectName(_fromUtf8("label_paneinfo_1"))

        self.retranslateUi(Form_TestPattern)
        QtCore.QMetaObject.connectSlotsByName(Form_TestPattern)

    def retranslateUi(self, Form_TestPattern):
        Form_TestPattern.setWindowTitle(_translate("Form_TestPattern", "Form_TestPattern", None))
        self.pushButton_addpattern.setText(_translate("Form_TestPattern", "AddPat", None))
        self.pushButton_savepatToFile.setText(_translate("Form_TestPattern", "SaveToFile", None))
        self.pushButton_prev.setText(_translate("Form_TestPattern", "PREV", None))
        self.pushButton_next.setText(_translate("Form_TestPattern", "NEXT", None))
        self.label_patindex.setText(_translate("Form_TestPattern", "Pattern Index:", None))
        self.pushButton_readpanel.setText(_translate("Form_TestPattern", "GetPanelInfo", None))
        self.pushButton_loadpatfromFile.setText(_translate("Form_TestPattern", "LoadfromFile", None))
        self.label_patdelay.setText(_translate("Form_TestPattern", "Curretn Pat delay time(second):", None))
        self.pushButton_delpattern.setText(_translate("Form_TestPattern", "DelPat", None))
        self.pushButton_sendpattochip.setText(_translate("Form_TestPattern", "SendToChip", None))
        self.pushButton_savecurrentpat.setText(_translate("Form_TestPattern", "SaveCurPat", None))
        self.pushButton_readfromchip.setText(_translate("Form_TestPattern", "ReadFromChip", None))
        __sortingEnabled = self.tableWidget_pattern.isSortingEnabled()
        self.tableWidget_pattern.setSortingEnabled(False)
        item = self.tableWidget_pattern.item(0, 0)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 1)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 2)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 3)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(0, 4)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(0, 5)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(0, 6)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(0, 7)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 0)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 1)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 2)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 3)
        item.setText(_translate("Form_TestPattern", "1", None))
        item = self.tableWidget_pattern.item(1, 4)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(1, 5)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(1, 6)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(1, 7)
        item.setText(_translate("Form_TestPattern", "0", None))
        item = self.tableWidget_pattern.item(2, 0)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 1)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 2)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 3)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(2, 4)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(2, 5)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(2, 6)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(2, 7)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 0)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 1)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 2)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 3)
        item.setText(_translate("Form_TestPattern", "3", None))
        item = self.tableWidget_pattern.item(3, 4)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(3, 5)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(3, 6)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(3, 7)
        item.setText(_translate("Form_TestPattern", "2", None))
        item = self.tableWidget_pattern.item(4, 0)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 1)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 2)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 3)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(4, 4)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(4, 5)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(4, 6)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(4, 7)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 0)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 1)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 2)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 3)
        item.setText(_translate("Form_TestPattern", "5", None))
        item = self.tableWidget_pattern.item(5, 4)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(5, 5)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(5, 6)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(5, 7)
        item.setText(_translate("Form_TestPattern", "4", None))
        item = self.tableWidget_pattern.item(6, 0)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 1)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 2)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 3)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(6, 4)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(6, 5)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(6, 6)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(6, 7)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 0)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 1)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 2)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 3)
        item.setText(_translate("Form_TestPattern", "7", None))
        item = self.tableWidget_pattern.item(7, 4)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(7, 5)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(7, 6)
        item.setText(_translate("Form_TestPattern", "6", None))
        item = self.tableWidget_pattern.item(7, 7)
        item.setText(_translate("Form_TestPattern", "6", None))
        self.tableWidget_pattern.setSortingEnabled(__sortingEnabled)
        self.label_paneinfo_1.setText(_translate("Form_TestPattern", "PanelInfo: 16,  LEDX:=4  and LEDY =8", None))

