# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dimming_TestingPattern_SX7.ui'
#
# Created: Mon Mar 13 18:14:48 2017
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(769, 572)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("222.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 170, 371, 291))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tableWidget_pattern = QtGui.QTableWidget(self.tab)
        self.tableWidget_pattern.setGeometry(QtCore.QRect(0, 0, 381, 261))
        self.tableWidget_pattern.setRowCount(8)
        self.tableWidget_pattern.setColumnCount(8)
        self.tableWidget_pattern.setObjectName(_fromUtf8("tableWidget_pattern"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(1, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(2, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(3, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(4, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(5, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(6, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_pattern.setItem(7, 7, item)
        self.tableWidget_pattern.horizontalHeader().setVisible(False)
        self.tableWidget_pattern.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget_pattern.horizontalHeader().setMinimumSectionSize(21)
        self.tableWidget_pattern.verticalHeader().setVisible(False)
        self.tableWidget_pattern.verticalHeader().setHighlightSections(True)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.pushButton_addpattern = QtGui.QPushButton(self.centralwidget)
        self.pushButton_addpattern.setGeometry(QtCore.QRect(220, 50, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addpattern.setFont(font)
        self.pushButton_addpattern.setObjectName(_fromUtf8("pushButton_addpattern"))
        self.spinBox_MemDataSelect = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_MemDataSelect.setEnabled(True)
        self.spinBox_MemDataSelect.setGeometry(QtCore.QRect(140, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_MemDataSelect.setFont(font)
        self.spinBox_MemDataSelect.setMinimum(0)
        self.spinBox_MemDataSelect.setProperty("value", 0)
        self.spinBox_MemDataSelect.setObjectName(_fromUtf8("spinBox_MemDataSelect"))
        self.pushButton_saveMemDataToFile = QtGui.QPushButton(self.centralwidget)
        self.pushButton_saveMemDataToFile.setEnabled(True)
        self.pushButton_saveMemDataToFile.setGeometry(QtCore.QRect(130, 110, 75, 23))
        self.pushButton_saveMemDataToFile.setObjectName(_fromUtf8("pushButton_saveMemDataToFile"))
        self.pushButton_prev = QtGui.QPushButton(self.centralwidget)
        self.pushButton_prev.setEnabled(True)
        self.pushButton_prev.setGeometry(QtCore.QRect(30, 60, 75, 41))
        self.pushButton_prev.setObjectName(_fromUtf8("pushButton_prev"))
        self.pushButton_next = QtGui.QPushButton(self.centralwidget)
        self.pushButton_next.setEnabled(True)
        self.pushButton_next.setGeometry(QtCore.QRect(130, 60, 75, 41))
        self.pushButton_next.setObjectName(_fromUtf8("pushButton_next"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_readpattern = QtGui.QPushButton(self.centralwidget)
        self.pushButton_readpattern.setGeometry(QtCore.QRect(220, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readpattern.setFont(font)
        self.pushButton_readpattern.setObjectName(_fromUtf8("pushButton_readpattern"))
        self.pushButton_loadMemDatafromFile = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loadMemDatafromFile.setEnabled(True)
        self.pushButton_loadMemDatafromFile.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.pushButton_loadMemDatafromFile.setObjectName(_fromUtf8("pushButton_loadMemDatafromFile"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(400, 10, 361, 441))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 470, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.spinBox_patdelays = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_patdelays.setEnabled(True)
        self.spinBox_patdelays.setGeometry(QtCore.QRect(250, 470, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_patdelays.setFont(font)
        self.spinBox_patdelays.setMinimum(0)
        self.spinBox_patdelays.setProperty("value", 0)
        self.spinBox_patdelays.setObjectName(_fromUtf8("spinBox_patdelays"))
        self.pushButton_delpattern = QtGui.QPushButton(self.centralwidget)
        self.pushButton_delpattern.setGeometry(QtCore.QRect(220, 90, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delpattern.setFont(font)
        self.pushButton_delpattern.setObjectName(_fromUtf8("pushButton_delpattern"))
        self.pushButton_sendpattochip = QtGui.QPushButton(self.centralwidget)
        self.pushButton_sendpattochip.setGeometry(QtCore.QRect(400, 460, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sendpattochip.setFont(font)
        self.pushButton_sendpattochip.setObjectName(_fromUtf8("pushButton_sendpattochip"))
        self.pushButton_savecurrentpat = QtGui.QPushButton(self.centralwidget)
        self.pushButton_savecurrentpat.setGeometry(QtCore.QRect(220, 130, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_savecurrentpat.setFont(font)
        self.pushButton_savecurrentpat.setObjectName(_fromUtf8("pushButton_savecurrentpat"))
        self.pushButton_readfromchip = QtGui.QPushButton(self.centralwidget)
        self.pushButton_readfromchip.setGeometry(QtCore.QRect(520, 460, 131, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_readfromchip.setFont(font)
        self.pushButton_readfromchip.setObjectName(_fromUtf8("pushButton_readfromchip"))
        self.comboBox_listpats = QtGui.QComboBox(self.centralwidget)
        self.comboBox_listpats.setGeometry(QtCore.QRect(30, 140, 69, 22))
        self.comboBox_listpats.setObjectName(_fromUtf8("comboBox_listpats"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setToolTip(_fromUtf8(""))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_setting_file = QtGui.QAction(MainWindow)
        self.actionOpen_setting_file.setObjectName(_fromUtf8("actionOpen_setting_file"))
        self.actionSave_setting_file = QtGui.QAction(MainWindow)
        self.actionSave_setting_file.setObjectName(_fromUtf8("actionSave_setting_file"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.menuFile.addAction(self.actionOpen_setting_file)
        self.menuFile.addAction(self.actionSave_setting_file)
        self.menuFile.addAction(self.actionQuit)
        self.menuSetting.addAction(self.actionConnect)
        self.menuSetting.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Dimming Debugger     DisConnect..", None))
        __sortingEnabled = self.tableWidget_pattern.isSortingEnabled()
        self.tableWidget_pattern.setSortingEnabled(False)
        item = self.tableWidget_pattern.item(0, 0)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(0, 1)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(0, 2)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(0, 3)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(0, 4)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(0, 5)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(0, 6)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(0, 7)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(1, 0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(1, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(1, 2)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(1, 3)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_pattern.item(1, 4)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(1, 5)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(1, 6)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(1, 7)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_pattern.item(2, 0)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(2, 1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(2, 2)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(2, 3)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(2, 4)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(2, 5)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(2, 6)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(2, 7)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(3, 0)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(3, 1)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(3, 2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(3, 3)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidget_pattern.item(3, 4)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(3, 5)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(3, 6)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(3, 7)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidget_pattern.item(4, 0)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(4, 1)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(4, 2)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(4, 3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(4, 4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(4, 5)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(4, 6)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(4, 7)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(5, 0)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(5, 1)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(5, 2)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(5, 3)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tableWidget_pattern.item(5, 4)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(5, 5)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(5, 6)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(5, 7)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidget_pattern.item(6, 0)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_pattern.item(6, 1)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_pattern.item(6, 2)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_pattern.item(6, 3)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_pattern.item(6, 4)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(6, 5)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(6, 6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(6, 7)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(7, 0)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(7, 1)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(7, 2)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(7, 3)
        item.setText(_translate("MainWindow", "7", None))
        item = self.tableWidget_pattern.item(7, 4)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_pattern.item(7, 5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_pattern.item(7, 6)
        item.setText(_translate("MainWindow", "6", None))
        item = self.tableWidget_pattern.item(7, 7)
        item.setText(_translate("MainWindow", "6", None))
        self.tableWidget_pattern.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "One Pattern", None))
        self.pushButton_addpattern.setText(_translate("MainWindow", "AddPat", None))
        self.pushButton_saveMemDataToFile.setText(_translate("MainWindow", "SaveToFile", None))
        self.pushButton_prev.setText(_translate("MainWindow", "PREV", None))
        self.pushButton_next.setText(_translate("MainWindow", "NEXT", None))
        self.label.setText(_translate("MainWindow", "Pattern Index:", None))
        self.pushButton_readpattern.setText(_translate("MainWindow", "ReadPat", None))
        self.pushButton_loadMemDatafromFile.setText(_translate("MainWindow", "LoadfromFile", None))
        self.label_2.setText(_translate("MainWindow", "Curretn Pat delay time(second):", None))
        self.pushButton_delpattern.setText(_translate("MainWindow", "DelPat", None))
        self.pushButton_sendpattochip.setText(_translate("MainWindow", "SendToChip", None))
        self.pushButton_savecurrentpat.setText(_translate("MainWindow", "SaveCurPat", None))
        self.pushButton_readfromchip.setText(_translate("MainWindow", "ReadFromChip", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_setting_file.setText(_translate("MainWindow", "Open setting file", None))
        self.actionSave_setting_file.setText(_translate("MainWindow", "Save setting file", None))
        self.actionQuit.setText(_translate("MainWindow", "quit", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))

